In [1]:
#standardization
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

[1.3 2.1 4.5 6.5]
3.6
2.046948949045872
After Scaling
[-1.12362353 -0.73279795  0.43967877  1.41674271]
0.0
0.9999999999999999


In [2]:
data=np.array([1.3,2.1,4.5,6.5])
print('Before scaling')
print(data)

mean=np.mean(data)
std=np.std(data)
print(np.mean(data))
print(np.std(data))

#data-mean/std
scaled_data=(data-mean)/std
print("After Scaling")
print(scaled_data)
print(np.mean(scaled_data))
print(np.std(scaled_data))

<IPython.core.display.Javascript object>

Before scaling
[1.3 2.1 4.5 6.5]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

3.6


<IPython.core.display.Javascript object>

2.046948949045872
After Scaling
[-1.12362353 -0.73279795  0.43967877  1.41674271]


<IPython.core.display.Javascript object>

0.0


<IPython.core.display.Javascript object>

0.9999999999999999


In [4]:
m=StandardScaler()   #setting standardscaler
data=np.array([1.3,2.1,4.5,6.5])  #creating an array
data=data.reshape(-1,1)    #as we have no of columns we will shape it to single column
print(data)

#fit_transform
m.fit(data)      #fitting a data 
m.fit_transform(data)     #fit and transform
mean=np.mean(data)       #mean of data
std=np.std(data)       #std deviation of data
print(np.mean(data))        
print(np.std(data))  

#data-mean/std
scaled_data=(data-mean)/std    #scaling a data 
print("After Scaling")     #values after scaling
print(scaled_data)         #getting scaled data 
print(np.mean(scaled_data))
print(np.std(scaled_data))

[[1.3]
 [2.1]
 [4.5]
 [6.5]]
3.6
2.046948949045872
After Scaling
[[-1.12362353]
 [-0.73279795]
 [ 0.43967877]
 [ 1.41674271]]
0.0
0.9999999999999999


### TRNASFORMATION ON DATA SET

In [9]:
from sklearn.preprocessing import StandardScaler
df= pd.read_csv("C:\\Users\\Pratik1\\Desktop\\dataset\\data's\\Bodyfat.csv")
# df=df.reshape(-1,1)
s=StandardScaler()
a=s.fit(df)
print(a)
sd_data=s.transform(df)
sd_data

print(np.mean(sd_data))
print(np.std(sd_data))
print(np.max(sd_data))

print("After fit transform")
sd_data=s.fit_transform(df)
print(np.mean(sd_data))
print(np.std(sd_data))
print(np.max(sd_data))

StandardScaler()
3.8769692923418165e-16
1.0
6.684808430933005
After fit transform
3.8769692923418165e-16
1.0
6.684808430933005


In [6]:
df.columns

Index(['Density', 'bodyfat', 'Age', 'Weight', 'Height', 'Neck', 'Chest',
       'Abdomen', 'Hip', 'Thigh', 'Knee', 'Ankle', 'Biceps', 'Forearm',
       'Wrist'],
      dtype='object')

### TRAIN TEST SPLIT

In [13]:
#loading a diabetes dataset
df=pd.read_csv("C:\\Users\\Pratik1\\Desktop\\dataset\\data's\\diabetes.csv")  
print(df)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [12]:
x=df.iloc[:,0:8]
print(x.columns)
x=df.drop(columns=["Outcome"])
print(x.columns)

y=df["Outcome"]
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')


<IPython.core.display.Javascript object>

(614, 8)
(154, 8)
(614,)
(154,)
